name: Slack action
description: Pushes notifications to slack
author: AMReX-Astro
inputs:
  slack_webhook:
    description: "URL for slack incoming webhook"
    required: true
  message:
    description: "notification message"
    required: false 
    default: ""
  pr_link: 
    description: "link to PR"
    required: false
    default: ""
  author_avatar:
    description: "get author avatar"
    required: false 
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
