name: Slack action
description: Pushes notifications to slack
author: AMReX-Astro
inputs:
  slack_webhook:
    description: "URL for slack incoming webhook"
    required: true
  message:
    description: "notification message"
    required: false 
    default: ""
  pr_link: 
    description: "link to PR"
    required: true
  author_avatar:
    description: "get author avatar"
    required: true
  commit_sha:
    description: "Commit SHA"
    required: true
  before_sha:
    description: "SHA of the previous commit"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
