name: Slack action
description: Pushes notifications to slack
author: AMReX-Astro
inputs:
  slack_webhook:
    description: "URL for slack incoming webhook"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
